apiVersion: batch/v1
kind: Job
metadata:
  name: docker-build-push
spec:
  template:
    metadata:
      name: docker-build-push
    spec:
      containers:
      - name: docker
        image: docker:1.10.0
        command: ["docker", "build", "-t", "job/cowsay:tag", "/home/demo/ndslabs-docker/cowsay"]
        securityContext: 
          privileged: true
        volumeMounts: 
        - name: dockersock 
          mountPath: /var/run/docker.sock
        - name: home 
          mountPath: /home/demo
      restartPolicy: Never
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: home
        hostPath:
          path: /tmp/volumes/demo
