apiVersion: v1
kind: Pod
metadata:
  name: docker-build-push
spec:
  containers:
  - name: docker
    image: docker:1.10.0
    command: ["docker", "build", "-t", "test/test", "/home/demo/developer-tutorial/example-1-cowsay"]
    securityContext: 
      privileged: true
    volumeMounts: 
    - name: dockersock 
      mountPath: /var/run/docker.sock
    - name: home 
      mountPath: /home/demo
  restartPolicy: Never
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
  - name: home
    hostPath:
      path: /tmp/volumes/demo
